#!/bin/sh

cd $HOME
ln -s .dotfiles/.gitconfig
ln -s .dotfiles/.bashrc
ln -s .dotfiles/.bash_profile
ln -s .dotfiles/.gitignore_global
ln -s .dotfiles/.tmux.conf
ln -s .dotfiles/.zshrc

touch .zshrc.mine
